name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: node -e "require('coffeescript/register'); require('./event.test')" \
        --test-reporter spec --test-reporter-destination stdout \
        --test-reporter node-test-github-reporter --test-reporter-destination stdout
