name: Post to slack

on:
  schedule:
    # 8am (EST) == 1pm (UTC) - minus one min to beat the rush of GH actions jobs, minus 1h for DST
    - cron:  '59 11 * * *'
    # 8pm Sunday (EST) == 1am Monday (UTC) - minus one min to beat the rush of GH actions jobs, minus 1h for DST
    - cron:  '59 23 * * 0'

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
      - run: npm i

      - name: Today
        if: github.event.schedule == '59 11 * * *'
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: '#events'
        run: |
          npx coffee github-action.coffee today

      - name: This week
        if: github.event.schedule == '59 23 * * 0'
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: '#events'
        run: |
          npx coffee github-action.coffee week
